### ISSUE TITLE
[Bug] 最新版 v2.22.0 执行./jms upgrade的时候报错 类型:bug

### ISSUE THREAD

**Issue by usami-muzugi** [jumpserver/installer#225]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**

**Bug 描述**
1. 执行upgrade 的时候，提示jms_core 容器已存在，已通过docker rm -f 解决
2. 执行upgrade 的时候，提示更新数据库失败：
MySQLdb._exceptions.OperationalError: (3780, "Referencing column 'session_id' and referenced column 'id' in foreign key constraint 'terminal_sessionrepl_session_id_228568d3_fk_terminal_' are incompatible.")

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/17221756/173778928-b8878a86-df4f-48a7-816b-037a28a8649d.png)

***错误日志***
```bash
root@jumpserver:/opt/jumpserver-installer-v2.22.2# ./jmsctl.sh upgrade 
Are you sure you want to update the current version to v2.22.2 ? (y/n)  (default y): 

1. Check Configuration File
Path to Configuration file: /opt/jumpserver/config
/opt/jumpserver/config/config.txt 	 [ √ ]
/opt/jumpserver/config/core/config.yml 	 [ √ ]
/opt/jumpserver/config/koko/config.yml 	 [ √ ]
/opt/jumpserver/config/mariadb/mariadb.cnf 	 [ √ ]
/opt/jumpserver/config/mysql/my.cnf 	 [ √ ]
/opt/jumpserver/config/nginx/lb_http_server.conf 	 [ √ ]
/opt/jumpserver/config/redis/redis.conf 	 [ √ ]
/opt/jumpserver/config/nginx/cert/server.crt  	 [ √ ]
/opt/jumpserver/config/nginx/cert/server.key  	 [ √ ]


complete


2. Loading Docker Image
[jumpserver/redis:6-alpine]
6-alpine: Pulling from jumpserver/redis
Digest: sha256:8300b885570faad626e569e7b8cfef3407c87050d705ff26e243200cb3f84da8
Status: Image is up to date for jumpserver/redis:6-alpine

[jumpserver/mysql:5]
5: Pulling from jumpserver/mysql
Digest: sha256:24fe4f4aaf4dd86920612aa925693da731dd35e6ab2146b860c8a2b3b750bd58
Status: Image is up to date for jumpserver/mysql:5

[jumpserver/web:v2.22.2]
v2.22.2: Pulling from jumpserver/web
Digest: sha256:6a39dac3d356b72702f9d6f3d179591b185ae5f0a8e01036903cfafaf75ce6d2
Status: Image is up to date for jumpserver/web:v2.22.2

[jumpserver/core:v2.22.2]
v2.22.2: Pulling from jumpserver/core
v2.22.2: Pulling from jumpserver/core
Digest: sha256:1e224bf28ec11e6f46dd840da7023002cc25cc059d954a0ac66166b4c8e11e2e
Status: Image is up to date for jumpserver/core:v2.22.2

[jumpserver/koko:v2.22.2]
v2.22.2: Pulling from jumpserver/koko
Digest: sha256:2d3d7765f01b2a29d3fae068943fdc6212ddcf28a5656c3c1f86a2b2265a7c5a
Status: Image is up to date for jumpserver/koko:v2.22.2

[jumpserver/lion:v2.22.2]
v2.22.2: Pulling from jumpserver/lion
Digest: sha256:1e5daf0245a8f6a87c79f669cbfe4f13e5b27a21796e61ea66bb7d14d6ac6980
Status: Image is up to date for jumpserver/lion:v2.22.2

[jumpserver/magnus:v2.22.2]
v2.22.2: Pulling from jumpserver/magnus
Digest: sha256:34a451e3d123df8833c4041e70ee687f3e43d15b58af484a15ae9f08f8c88a8a
Status: Image is up to date for jumpserver/magnus:v2.22.2

complete

3. Backup database
Backing up...
Creating jms_core ... done
mysqldump: [Warning] Using a password on the command line interface can be insecure.
[SUCCESS] Backup succeeded! The backup file has been saved to: /opt/jumpserver/db_backup/jumpserver-v2.19.2-2022-06-15_16:00:04.sql

4. Backup Configuration File
Back up to /opt/jumpserver/db_backup/config-v2.19.2-2022-06-15_16:00:08.conf

5. Apply database changes
Changing database schema may take a while, please wait patiently
Creating jms_core ... done
2022-06-15 16:00:14 Collect static files
2022-06-15 16:00:14 Collect static files done
2022-06-15 16:00:14 Check database structure change ...
2022-06-15 16:00:14 Migrate model change to database ...
2022-06-15 16:00:17 Perform migrate failed, exit
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (3780, "Referencing column 'session_id' and referenced column 'id' in foreign key constraint 'terminal_sessionrepl_session_id_228568d3_fk_terminal_' are incompatible.")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./jms", line 84, in perform_db_migrate
    management.call_command('migrate')
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 168, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 243, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 229, in apply_migration
    migration_recorded = True
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 115, in __exit__
    self.execute(sql)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 142, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (3780, "Referencing column 'session_id' and referenced column 'id' in foreign key constraint 'terminal_sessionrepl_session_id_228568d3_fk_terminal_' are incompatible.")
Operations to perform:
  Apply all migrations: acls, admin, applications, assets, audits, auth, authentication, captcha, common, contenttypes, django_cas_ng, django_celery_beat, jms_oidc_rp, notifications, ops, orgs, perms, rbac, sessions, settings, terminal, tickets, users
Running migrations:
  Applying rbac.0002_auto_20210929_1409... OK
  Applying rbac.0003_auto_20211130_1037...Update builtin Role: SystemAdmin - True
Update builtin Role: SystemAuditor - True
Update builtin Role: SystemComponent - True
Update builtin Role: User - True
Update builtin Role: OrgAdmin - True
Update builtin Role: OrgAuditor - True
Update builtin Role: OrgUser - True
 OK
  Applying rbac.0004_auto_20211201_1901... OK
  Applying orgs.0011_auto_20211223_1913... OK
  Applying orgs.0012_auto_20220118_1054... OK
  Applying perms.0024_auto_20220217_2135... OK
  Applying perms.0025_auto_20220223_1539... OK
  Applying perms.0026_auto_20220307_1500... OK
  Applying perms.0027_auto_20220310_1802... OK
  Applying perms.0028_auto_20220316_2028... OK
  Applying rbac.0005_auto_20220307_1524... OK
  Applying rbac.0006_auto_20220310_0616... OK
  Applying rbac.0007_auto_20220314_1525... OK
  Applying rbac.0008_auto_20220411_1709... OK
  Applying rbac.0009_auto_20220411_1724... OK
  Applying settings.0004_auto_20220211_1401... OK
  Applying settings.0005_auto_20220310_0616... OK
  Applying terminal.0043_auto_20220217_2135...[ERROR] Failed to change the table structure!
```

**Comment by wojiushixiaobai** [comment]
数据库字符集不能为 utf8mb4
